//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcvize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class akademisyenler
    {
        public int Id { get; set; }
        public string akademisyenad { get; set; }
        public string akademisyensoyad { get; set; }
        public string akademisyenbolum { get; set; }
        public Nullable<System.DateTime> akademisyenbaslangic { get; set; }
    }
}
