//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcvize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mezunlar
    {
        public int Id { get; set; }
        public string mezunad { get; set; }
        public string mezunbolum { get; set; }
        public Nullable<int> mezunpuan { get; set; }
    }
}
