//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcvize.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ogrenciler> ogrenciler { get; set; }
        public virtual DbSet<akademisyenler> akademisyenler { get; set; }
        public virtual DbSet<birimler> birimler { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<mezunlar> mezunlar { get; set; }
        public virtual DbSet<raporlar> raporlar { get; set; }
    }
}
