//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcvize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenciler
    {
        public int Id { get; set; }
        public string ogrenciad { get; set; }
        public Nullable<int> ogrencino { get; set; }
        public string ogrencibolum { get; set; }
        public string ogrencipuan { get; set; }
    }
}
